### PR TITLE
Fixt bug

### PR DESCRIPTION
**Pull request by RafMo20D**
Make "HMSS" an instance variable   HH:mm:ss, S

### CODE REVIEW

**Comment by ArtsiomCh** [comment]
Hi @RafMo20D Thanks for contribution! What's is the purpose of that change? What problem you're trying to solve?

**Comment by RafMo20D** [comment]
Thanks  @ArtsiomCh  Fixt bug  The problem is the clock of two betrayed  HH:mm:ss,S 

H:mm:ss,S

**Comment by RafMo20D** [comment]
SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss:aa");
    System.out.println(dateFormat.format(fromDateTime.getTime()));
    System.out.println(dateFormat.format(toDateTime.getTime()));

**Comment by ArtsiomCh** [comment]
> Thanks @ArtsiomCh Fixt bug The problem is the clock of two betrayed HH:mm:ss,S
> 
> H:mm:ss,S

Why do you think there is a bug/problem here?
Variable `HMSS` is not used anywhere and even if used - it's just for internal debug logging
So, probably proper fix here will deleting `HMSS` at all...

**Comment by RafMo20D** [comment]
yes deleting HMSS at all  And you, what do you think is better? I want to know something new

**Comment by ArtsiomCh** [comment]
Please verify the code before committing. `mmssSSS` we still using in the code. Only `HMSS` (whole line) need to be deleted (probably with usage in committed code below in the file).
Also could you please remove/squash all unrelated commits?

**Comment by RafMo20D** [comment]
> Please verify the code before committing. `mmssSSS` we still using in the code. Only `HMSS` (whole line) need to be deleted (probably with usage in committed code below in the file). Also could you please remove/squash all unrelated commits?

ok Thanks

**Comment by RafMo20D** [comment]
The whole line was debug deleted and everything worked

**Comment by ArtsiomCh** [comment]
Good try, but no and you know why.

**Pull request closed without merging**
